package modelo.entidad;
// Generated 8/10/2022 11:54:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private Integer idLibro;
     private Categoria categoria;
     private Tipo tipo;
     private String titulo;
     private String isbn;
     private String autor;
     private int estado;
     private Set<Prestamo> prestamos = new HashSet<Prestamo>(0);

    public Libro() {
    }

	
    public Libro(Categoria categoria, Tipo tipo, String titulo, String isbn, String autor, int estado) {
        this.categoria = categoria;
        this.tipo = tipo;
        this.titulo = titulo;
        this.isbn = isbn;
        this.autor = autor;
        this.estado = estado;
    }
    public Libro(Categoria categoria, Tipo tipo, String titulo, String isbn, String autor, int estado, Set<Prestamo> prestamos) {
       this.categoria = categoria;
       this.tipo = tipo;
       this.titulo = titulo;
       this.isbn = isbn;
       this.autor = autor;
       this.estado = estado;
       this.prestamos = prestamos;
    }
   
    public Integer getIdLibro() {
        return this.idLibro;
    }
    
    public void setIdLibro(Integer idLibro) {
        this.idLibro = idLibro;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set<Prestamo> getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set<Prestamo> prestamos) {
        this.prestamos = prestamos;
    }




}


